---
# control
control:
  data_name: fpb-sa
  model_name: bart-base
  task_name: s2s
  ft_name: lora
# experiment
pin_memory: True
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
verbose: False
